version: '3.8'

services:
  db:
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=distribcalc
      - POSTGRES_PASSWORD=ZVo2buR4oRA5fEq0fb5o
      - POSTGRES_USER=calc
    image: postgres:16.2-alpine
